name       : perl-image-sane
version    : '5'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/R/RA/RATCLIFFE/Image-Sane-5.tar.gz : 229aa0e9f049efa760f3c2f6e61d9d539af43d8f764b50a6e03064b4729a35ff
homepage   : https://metacpan.org/release/Image-Sane
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl extension for the SANE Project
description: |
    This module allows you to access SANE-compatible scanners in a Perlish and object-oriented way, freeing you from the casting and memory management in C, yet remaining very close in spirit to original API.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(sane-backends)
    - perl-class-data-inheritable
    - perl-devel-stacktrace
    - perl-exception-class
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-readonly
    - perl-test-requires
    - perl-try-tiny
    - perl-test-pod
rundeps    :
    - perl-exception-class
    - perl-readonly
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
