name       : perl-image-sane
version    : 0.14
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RA/RATCLIFFE/Image-Sane-0.14.tar.gz : a4b027c9b7650291f1acb0eb93861a7fc45aef4e08f6726843f174fa113c8ba5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl extension for the SANE Project
description: |
    This module allows you to access SANE-compatible scanners in a Perlish and object-oriented way, freeing you from the casting and memory management in C, yet remaining very close in spirit to original API.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(sane-backends)
    - perl-class-data-inheritable
    - perl-devel-stacktrace
    - perl-exception-class
    - perl-extutils-depends
    - perl-extutils-pkgconfig
    - perl-readonly
    - perl-test-requires
    - perl-try-tiny
    - perl-test-pod
rundeps    :
    - perl-exception-class
    - perl-readonly
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
